### PR TITLE
Mavenize

### PR DESCRIPTION
**Pull request by celeduc**
* Added Maven support while maintaining Ant support
* Added version metadata to the JAR files produced by Ant
* Ant dependency & build cleanup

** Note: after merging, `v1.0.0` needs to be tagged for JitPack to work **

### CODE REVIEW

**Comment by ianopolous** [comment]
@celeduc Any chance I could get you to work your maven magic on the Cid repo too?  https://github.com/ipld/java-cid/
People are clamouring for maven support, but not respecting the ant build with vendored libs.

**Comment by celeduc** [comment]
@ianopolous Done :)

**Comment by ianopolous** [comment]
Thank you!

**Comment by ianopolous** [comment]
Does https://github.com/ipfs/java-ipfs-api need updating for maven now?

**Pull request merged**
