### PR TITLE
Correct implementation of Base16, Base32 and base64 encodings

### PR DESCRIPTION
**Pull request by odisseus**
I decided to write these from scratch instead of copying or linking the [implementation](https://github.com/Peergos/Peergos/tree/master/src/peergos/shared/io/ipfs/multibase) from Peergos, because the latter's AGPL license is not compatible with the [project](https://github.com/propensive/fury) in which I'm going to use this.

This pull request also includes changes from #15.

### CODE REVIEW

**Comment by ianopolous** [comment]
If you look closer, the implementation in Peergos is actually Apache licensed mainly. Anything that is not, I wrote and I'm happy to relicense as MIT for this project, which is what I've done so far. It has also been extensively tested.

**Comment by coreagile** [comment]
What is keeping this from being merged?

**Comment by ianopolous** [comment]
> What is keeping this from being merged?

It is incorrect. See e.g.
{Multibase.Base.Base32, hexToBytes("446563656e7472616c697a652065766572797468696e67212121"), "birswgzloorzgc3djpjssazlwmvzhs5dinfxgoijbee"}, which is taken from go-multibase tests

**Comment by odisseus** [comment]
How is it incorrect? I have just [added](https://github.com/odisseus/java-multibase/commit/bd8b24543a2ff1ac622d21b36c5df50c500233cb) this example to my test, and it seems that it is both encoded and decoded correctly.

**Pull request closed without merging**
